routes/web.php
<?php

use App\Http\Controllers\Admin\BidDocumentsController;
use App\Http\Controllers\Admin\BidsController;
use App\Http\Controllers\Admin\CommentsController;
use App\Http\Controllers\Admin\DocumentApproversController;
use App\Http\Controllers\Admin\DocumentsController;
use App\Http\Controllers\Admin\ProcessesController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Pages\PagesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

Route::prefix('users')->group(function () {
    Route::post('/create', [UsersController::class, 'create'])->name('site.users.create');
});

Route::prefix('pages')->group(function (){
    Route::get('/bids', [PagesController::class, 'bids'])->name('pages.bids');
    Route::post('/bids/create', [BidsController::class, 'create'])->name('site.bids.create');
});

Route::middleware('auth')->prefix('admin')->group(function () {

    Route::get('/users-register-form', [UsersController::class, 'showRegistrationForm'])->name('users.registerForm');
    Route::get('/bids-create-form', [BidsController::class, 'showCreateForm'])->name('bids.createForm');

    Route::prefix('users')->group(function () {
        Route::get('/all', [UsersController::class, 'index'])->name('users.all');
        Route::post('/create', [UsersController::class, 'create'])->name('users.create');
        Route::delete('/delete/{userId}', [UsersController::class, 'destroy'])->name('users.delete');
    });

    Route::prefix('bids')->group(function () {
        Route::get('/all', [BidsController::class, 'index'])->name('bids.all');
        Route::get('/my', [BidsController::class, 'my'])->name('bids.my');
        Route::get('/show/{id}', [BidsController::class, 'show'])->name('bids.show');
        Route::post('/update', [BidsController::class, 'update'])->name('bids.update');
        Route::post('/create', [BidsController::class, 'create'])->name('bids.create');
    });

    Route::prefix('bid-documents')->group(function () {
        Route::post('/update', [BidDocumentsController::class, 'update'])->name('bid.document.update');
    });


    Route::prefix('documents')->group(function () {
        Route::get('/all', [DocumentsController::class, 'index'])->name('documents.all');
        Route::get('/show/{id}', [DocumentsController::class, 'show'])->name('documents.show');
        Route::get('/render', [DocumentsController::class, 'renderPdf'])->name('documents.render');
        Route::post('/set-active', [DocumentsController::class, 'setActive'])->name('documents.setActive');
    });

    Route::prefix('document-approves')->group(function () {
        Route::post('/create', [DocumentApproversController::class, 'create'])->name('document.approve.create');
        Route::delete('/delete', [DocumentApproversController::class, 'delete'])->name('document.approve.delete');
        Route::post('/status', [DocumentApproversController::class, 'changeStatus'])->name('document.approve.status');
    });

    Route::prefix('comments')->group(function () {
            Route::post('/create', [CommentsController::class, 'create'])->name('comments.create');
    });

    Route::prefix('processes')->group(function () {
        Route::get('/all', [ProcessesController::class, 'index'])->name('processes.all');
    });

});

app/Models/BidDocument.php
<?php

namespace App\Models;

use App\Services\BidsService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class BidDocument extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();

        static::saved(function(BidDocument $bidDocument) {
            if ($bidDocument->documents->count()) {
                BidsService::generateBidDocumentPdf($bidDocument->id);
            }
        });
    }

    public function bid(): BelongsTo
    {
        return $this->belongsTo(Bid::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(BidDocumentItem::class);
    }

    public function documents(): MorphMany
    {
        return $this->morphMany(Document::class, 'documentable')->orderBy('id', 'DESC');
    }

    public function getVersionsCountAttribute(): int
    {
        return $this->documents()->count();
    }

    public function getResponsibleUserAttribute()
    {
        return $this->bid->responsibleUser;
    }

    public function getSourceAttribute()
    {
        return $this->bid;
    }

    public function getSourceRouteAttribute()
    {
        return route('bids.show', ['id' => $this->bid->id]);
    }

}

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $guarded = [];

    public function documentable()
    {
        return $this->morphTo();
    }

    public function comments()
    {
        return $this->hasMany(DocumentComment::class)->orderByDesc('id');
    }

    public function approves()
    {
        return $this->hasMany(DocumentApprover::class);
    }

    public function getTemplateAttribute()
    {
        switch ($this->documentable_type) {
            case BidDocument::class:
                $template = 'Заявка на организацию мероприятия';
                break;
            default:
                $template = '-';
        }

        return $template;
    }

    public function getIsApprovedAttribute(): int
    {
        return 0;
    }
}

app/Http/Controllers/Admin/DocumentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\PdfHelper;
use App\Http\Controllers\Controller;
use App\Models\Document;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class DocumentsController extends Controller
{
    public function index()
    {
        $documents = Document::orderByDesc('id')->groupBy('documentable_type')->groupBy('documentable_id')->get();

        return view('admin.documents.index', ['pageTitle' => 'Документы', 'documents' => $documents]);
    }

    public function show(int $id)
    {
        $document = Document::find($id);

        $entity = $document->documentable;

        $allDocuments = $entity->documents;

        $users = User::all();

        return view('admin.documents.show', ['pageTitle' => "История документа #$document->id", 'documents' => $allDocuments, 'users' => $users]);
    }

    public function renderPdf(Request $request)
    {
        $pdfcontent = PdfHelper::getPdfContent($request->pdf);

        return Response::make($pdfcontent, 200, ['content-type'=>'application/pdf']);
    }

    public function setActive(Request $request)
    {
        $document = Document::find($request->id);

        Document::where('documentable_type', $document->documentable_type)
            ->where('documentable_id', $document->documentable_id)
            ->update(['active' => 0]);

        $document->active = 1;
        $document->save();

        return redirect(route('documents.show', ['id' => $document->id]));
    }
}

resources/views/admin/documents/index.blade.php
@extends('layouts.app')

@section('content')
    <hr>
{{--    @if(request()->route()->getName() === 'documents.all')--}}
{{--        <a href="{{ route('bids.createForm') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline">--}}
{{--            <button type="button" class="btn btn-outline-success">Создать</button>--}}
{{--        </a>--}}
{{--        <hr>--}}
{{--    @endif--}}
    <form action="{{ route('documents.all') }}" method="GET">
        <div class="mb-2 row">
            <div class="col-sm-2">
                <input type="text" class="form-control" id="search" name="search" placeholder="Введите для поиска" value="{{ request('search') ?? '' }}">
            </div>
{{--            @if(request()->route()->getName() === 'documents.all')--}}
{{--                <select class="form-select col-sm-2" id="responsible" name="responsible"--}}
{{--                        style="width: auto; margin-right: 10px;">--}}
{{--                    <option value="0">--}}
{{--                        Выберите менеджера--}}
{{--                    </option>--}}
{{--                    @foreach($managers as $manager)--}}
{{--                        <option value="{{ $manager->id }}" @if(request('responsible') == $manager->id) selected @endif>--}}
{{--                            {{ $manager->name }}--}}
{{--                        </option>--}}
{{--                    @endforeach--}}
{{--                </select>--}}
{{--            @endif--}}
            <button type="submit" class="col-sm-1 btn btn-success">Поиск</button>
        </div>
    </form>

    <form action="{{ route('documents.all') }}" method="GET">
        <button type="submit" class="col-sm-1 btn btn-warning">Очистить</button>
    </form>

    <table class="table mt-3">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Шаблон</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Автор</th>
            <th scope="col">Кол-во версий</th>
            <th scope="col">История</th>
            <th scope="col">Одобрено</th>
        </tr>
        </thead>
        <tbody>
        @foreach($documents as $document)
            <tr>
                <td>{{ $document->id }}</td>
                <td>{{ $document->template }}</td>
                <td>{{ $document->created_at }}</td>
                <td>{{ $document->documentable->responsibleUser->name }}</td>
                <td>{{ $document->documentable->versionsCount }}</td>
                <td><a href="{{ route('documents.show', ['id' => $document->id]) }}">История</a></td>
                <td>{{ $document->isApproved ? 'Да' : 'Нет' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/documents/show.blade.php
@extends('layouts.app')

@section('content')
    @if($documents->where('active', 1)->count())
        <div class="mt-3 generate">
            <div class="alert alert-warning" role="alert">
                Существует активная версия документа. Вы можете
                <a href="#">генерировать финальную версию документа</a> и завершить работу над этим документом.
            </div>
        </div>
    @endif
    <div class="history mt-3">
        <h4>Версии</h4>
        <table class="table table-success table-striped">
            <thead>
            <tr>
                <th scope="col">№ версии</th>
                <th scope="col">Дата</th>
                <th scope="col">Автор</th>
                <th scope="col">Документ</th>
                <th scope="col">Комментарии</th>
                <th scope="col">Активная версия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($documents as $index => $document)
                <tr>
                    <td>{{ $documents->count() - $index }}</td>
                    <td>{{ $document->created_at }}</td>
                    <td>{{ $document->documentable->responsibleUser->name }}</td>
                    <td><a href="#{{ $document->id }}">{{ $document->file }}</a></td>
                    <td>{{ $document->comments->count() }}</td>
                    <td>{{ $document->active ? 'Да' : '-' }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @foreach($documents as $document)
        <hr>
        <div class="d-flex align-items-center">
            <h5 id="{{ $document->id }}">Документ №{{ $document->id }}</h5>
            @if($document->active)
                <div class="btn-success" style="margin-left: 5px;">Активен</div>
            @else
                <form action="{{ route('documents.setActive') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id" value="{{ $document->id }}">
                    <button type="submit" class="btn btn-outline-success mt-2" style="margin-left: 5px;">Сделать
                        активным
                    </button>
                </form>
            @endif

        </div>

        <div class="d-flex mt-2">
            <iframe src="{{ route('documents.render', ['pdf' => $document->file]) }}"
                    style="width:50%;height:800px"></iframe>
            <div class="col-6" style="margin-left: 20px;">
                <h4>Информация</h4>
                <div class="data">
                    <p>Автор: {{ $document->documentable->responsibleUser->name }}</p>
                    <p>Дата создания: {{ $document->created_at }}</p>
                    <p>Источник: <a
                            href="{{ $document->documentable->sourceRoute }}">{{ $document->documentable->source->title }}</a>
                    </p>
                </div>
                <div class="comments">
                    <h4>Комментарии</h4>
                    <div class="row d-flex justify-content-center">
                        <div class="col-md-8 col-lg-10">
                            <div class="card shadow-0 border" style="background-color: #f0f2f5;">
                                <div class="card-body p-4">
                                    <div class="form-outline mb-4">
                                        <form action="{{ route('comments.create') }}" method="POST">
                                            <div class="d-flex">
                                                @csrf
                                                <input type="text" id="addANote" class="form-control" name="text"
                                                       placeholder="Добавьте комментарий...">
                                                <input type="hidden" name="document_id" value="{{ $document->id }}">
                                                <button type="submit" class="btn btn-outline-info"
                                                        style="margin-left: 5px;">Добавить
                                                </button>
                                            </div>
                                        </form>

                                        <div class="form-notch">
                                            <div class="form-notch-leading" style="width: 9px;">
                                            </div>
                                            <div class="form-notch-middle" style="width: 80px;">
                                            </div>
                                            <div class="form-notch-trailing">
                                            </div>
                                        </div>
                                    </div>

                                    @foreach($document->comments as $comment)
                                        <div class="card mt-2">
                                            <div class="card-body">
                                                <p class="small"><span><em>{{ $comment->created_at }}</em></span></p>
                                                <p>{{ $comment->text }}</p>

                                                <div class="d-flex justify-content-between">
                                                    <div class="d-flex flex-row align-items-center">
                                                        <p class="small mb-0 ms-2">
                                                            <span>{{ $comment->user->role->name }} </span>{{ $comment->user->name }}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                @if($document->active)
                    <div class="approved mt-3">
                        <h4>Подтверждение</h4>
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-12 col-lg-12">
                                <div class="card shadow-0 border" style="background-color: #f0f2f5;">
                                    <div class="card-body p-4">
                                        <div class="form-outline mb-4">
                                            <form action="{{ route('document.approve.create') }}" method="POST">
                                                <div class="d-flex">
                                                    @csrf
                                                    <input type="hidden" value="{{ $document->id }}" name="documentId">
                                                    <select class="form-select" aria-label="Default select example"
                                                            name="userId">
                                                        <option value="0">
                                                            Выберите
                                                        </option>
                                                        @foreach($users as $user)
                                                            <option value="{{ $user->id }}">
                                                                {{ $user->name }}
                                                            </option>
                                                        @endforeach
                                                    </select>
                                                    <button type="submit" class="btn btn-outline-info"
                                                            style="margin-left: 5px;">Добавить
                                                    </button>
                                                </div>
                                            </form>

                                            <div>
                                                @foreach($document->approves as $approve)
                                                    <div class="d-flex align-items-center mt-2">
                                                        <div class="ruling d-flex">
                                                            @if($approve->approved !== \App\Models\Enums\ApproveStatusesEnum::YES)
                                                                <form action="{{ route('document.approve.delete') }}"
                                                                      method="POST">
                                                                    @method('DELETE')
                                                                    @csrf
                                                                    <input type="hidden" name="approveId"
                                                                           value="{{ $approve->id }}">
                                                                    <button type="submit"
                                                                            class="btn btn-danger fs-7 bi-trash3"></button>
                                                                </form>
                                                                @if(auth()->user()->id === $approve->user_id)
                                                                    <form style="margin-left: 4px;"
                                                                          action="{{ route('document.approve.status', ['status' => \App\Models\Enums\ApproveStatusesEnum::YES]) }}"
                                                                          method="POST">
                                                                        @csrf
                                                                        <input type="hidden" name="approveId"
                                                                               value="{{ $approve->id }}">
                                                                        <button type="submit"
                                                                                class="btn btn-success fs-7 bi-check-circle"></button>
                                                                    </form>
                                                                    <form style="margin-left: 5px;"
                                                                          action="{{ route('document.approve.status', ['status' => \App\Models\Enums\ApproveStatusesEnum::NO]) }}"
                                                                          method="POST">
                                                                        @csrf
                                                                        <input type="hidden" name="approveId"
                                                                               value="{{ $approve->id }}">
                                                                        <button type="submit"
                                                                                class="btn btn-warning fs-7 bi-x-circle"></button>
                                                                    </form>
                                                                @endif
                                                            @endif
                                                        </div>

                                                        <div style="margin-left: 5px;">{{ $approve->user->name }}:
                                                            <b>{{ \App\Models\Enums\ApproveStatusesEnum::STATUSES[$approve->approved]}}</b>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

            </div>
        </div>
    @endforeach

@endsection